[package]
name = "phidget"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
authors = ["Frank Pagliughi <fpagliughi@mindspring.com>"]
repository = "https://github.com/fpagliughi/phidget-rs"
license = "MIT"
readme = "README.md"
keywords = ["linux", "embedded", "analog", "iio"]
categories = ["embedded", "hardware-support"]
description = """
Phidget library for Rust
"""

[dependencies]
phidget-sys = { version = "0.1", path = "phidget-sys" }
thiserror = "1.0"
anyhow = "1.0"