[package]
name = "phidget"
version = "0.1.1"
edition = "2021"
rust-version = "1.75"
authors = ["Frank Pagliughi <fpagliughi@mindspring.com>"]
repository = "https://github.com/fpagliughi/phidget-rs"
license = "MIT"
readme = "README.md"
keywords = ["linux", "embedded", "analog", "iio"]
categories = ["embedded", "hardware-support"]
description = """
Phidget library for Rust
"""

[features]
default = ["utils"]
utils = ["anyhow", "ctrlc"]

[dependencies]
phidget-sys = { version = "0.1.1", path = "phidget-sys" }
anyhow = { version = "1.0.79", optional = true }
ctrlc = { version = "3.4.2", features = [ "termination" ], optional = true }

[dev-dependencies]
anyhow = "1.0.79"
ctrlc = { version = "3.4.2", features = [ "termination" ] }

[[bin]]
name = "phidget"
required-features = ["utils"]